version: '3.8'

services:
  python-flask-app-container:
    image: 997909799/python-flask-app:V1.0.0
    container_name: python-flask-app-container
    ports:
      - 5002:5000
    volumes:
      - ./:/app
    networks:
      - mysql-python-app-network
    
  mysql-flask-app-container:
    image: mysql:8.0.28
    container_name: mysql-flask-app-container
    restart: always
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST= "%"
    networks:
      - mysql-python-app-network
    volumes:
      - mysql-python-app-volume:/var/lib/mysql
      - mysql-python-app-volume-config:/etc/mysql
    
  phpmyadmin8-flask-app-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8-flask-app-container
    restart: always
    ports:
      - 8088:80
    networks: 
      - mysql-python-app-network
    environment:
      PMA_HOST: mysql-flask-app-container
  
  mysql5-flask-app-container:
    image: mysql:5.7.43
    container_name: mysql5-flask-app-container
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST= "%"
    networks:
      - mysql-python-app-network
    
  phpmyadmin5-flask-app-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin5-flask-app-container
    restart: always
    ports:
      - 8089:80
    networks: 
      - mysql-python-app-network
    environment:
      PMA_HOST: mysql5-flask-app-container
  
  sqlserver2022-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022-container
    restart: always
    ports:
      - 1434:1433
    environment:
      - SA_PASSWORD=Abc@12345678
      - ACCEPT_EULA= Y
    networks:
      - mysql-python-app-network
    
networks:
  mysql-python-app-network:
    name: mysql-python-app-networks
volumes:
  mysql-python-app-volume:
  mysql-python-app-volume-config: